# Generated by Django 6.0.7 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('done', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', max_length=20)),
                ('total_blocks', models.PositiveIntegerField(default=0)),
                ('current_block', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
