# Generated by Django 6.0.7 on 2026-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionjob',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='retry_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='retry_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='retry_wait_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('running', 'Processando'), ('done', 'Concluído'), ('failed', 'Falhou')], default='queued', max_length=20),
        ),
    ]
