# Generated by Django 6.0.7 on 2026-07-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_conversionjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='fix_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='fix_max',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
