# Generated by Django 6.0.7 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_conversionjob_fix_attempt_conversionjob_fix_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
