# Generated by Django 6.0.7 on 2026-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_conversionjob_needs_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='original_filename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='original_pdf',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='result_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='results/'),
        ),
    ]
