"""
Django settings for pdf2md_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: don't run with debug turned on in production!
# Default FALSE: falhar fechado. Com default True, uma variavel de ambiente nao setada
# (ou escrita errada) no Render deixava o servico em DEBUG — vazando traceback e settings,
# e pulando todo o bloco de hardening no fim deste arquivo. Para desenvolver local,
# DJANGO_DEBUG=True esta no .env.example.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        # Nao cair no fallback embutido em producao: a chave estaria publicada no
        # repositorio, permitindo forjar cookie assinado e token CSRF.
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY nao definida. Obrigatoria quando DJANGO_DEBUG != True.'
        )
    SECRET_KEY = 'django-insecure-chave-apenas-para-desenvolvimento-local'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]

# O Render expõe o hostname público do serviço nessa variável de ambiente.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_API_KEY_CONVERTER   = os.environ.get('GEMINI_API_KEY_CONVERTER', '') or GEMINI_API_KEY
GEMINI_API_KEY_VALIDATOR   = os.environ.get('GEMINI_API_KEY_VALIDATOR', '') or GEMINI_API_KEY
GEMINI_API_KEY_RECONVERTER = os.environ.get('GEMINI_API_KEY_RECONVERTER', '') or GEMINI_API_KEY
GEMINI_API_KEY_META        = os.environ.get('GEMINI_API_KEY_META', '') or GEMINI_API_KEY
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.1-flash-lite')
PDF_BLOCK_SIZE = int(os.environ.get('PDF_BLOCK_SIZE', '5'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'converter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf2md_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf2md_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASE_URL era documentado como suportado, mas nunca era lido: `dj-database-url` estava
# no requirements sem nenhum uso, e plugar um Postgres no Render nao mudava nada — todo o
# estado dos jobs continuava no SQLite efemero, que some no restart.
# OPTIONS so valem para SQLite: WAL deixa leitura e escrita concorrerem (o worker grava o
# progresso do job a cada bloco enquanto a tela da fila le a cada 1,5s), e o timeout evita
# "database is locked" nos picos, ja que o Gunicorn roda com --threads=4 e ha 3 threads de
# worker gravando.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}
if DATABASES['default'].get('ENGINE', '').endswith('sqlite3'):
    DATABASES['default'].setdefault('OPTIONS', {}).update({
        'timeout': 20,
        'init_command': 'PRAGMA journal_mode=WAL;',
    })


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Uploaded PDFs e Markdown gerados: armazenamento local efêmero de propósito —
# em produção (Render free tier) esses arquivos somem quando o serviço reinicia,
# o que é aceitável pois o uso é só durante o processamento/download da sessão.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# NAO subir FILE_UPLOAD_MAX_MEMORY_SIZE. Ele é o limiar acima do qual o Django para de
# segurar o upload na RAM e passa a gravar em arquivo temporário; com 200 MB, um envio
# grande (ou 2-4 simultâneos, já que o Gunicorn roda --threads=4) estourava os 512 MB do
# Render free tier e derrubava o worker por OOM. No default (2,5 MB) o arquivo é spoolado
# pro disco e nada no pipeline precisa dele em memória — o splitter lê pelo caminho.
# DATA_UPLOAD_MAX_MEMORY_SIZE também não precisava ser mexido: ele mede o corpo da
# requisição EXCLUINDO os arquivos enviados, então nunca foi o que rejeitava PDF grande.
# O limite de tamanho de PDF é aplicado em forms.py:clean_pdf_files, onde dá pra devolver
# mensagem de erro em vez de 400 seco.
# Uploads múltiplos: o default de DATA_UPLOAD_MAX_NUMBER_FILES (100) vale e é intencional.
MAX_PDF_BYTES = int(os.environ.get('MAX_PDF_BYTES', 200 * 1024 * 1024))  # 200 MB por arquivo

# Segurança extra quando rodando em produção (Render sempre serve via HTTPS).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD fica desligado de propósito: preload é submissão a uma lista
    # embutida nos navegadores, difícil de reverter, e o serviço roda sob um domínio
    # compartilhado (*.onrender.com). Só faz sentido com domínio próprio e HTTPS garantido
    # em todos os subdomínios.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
